name: CI for app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: config node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: inst make
        run: sudo apt-get install -y make

      - name: start env
        run: make setup

      - name: start linter
        run: make lint

      - name: start test
        run: make test

        
